project:
  type: website
  output-dir: _site

website:
  title: "MOMENT Lab"
  site-url: https://mao-moment.github.io/

  page-footer:
    left: "&copy; 2026 MOMENT Lab"
    right: "Built with [Quarto](https://quarto.org/)"

  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Team"
        href: team.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Join Us"
        href: join.qmd

    right:
      - icon: github
        href: https://github.com/mao-moment

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left