project:
  type: website
  output-dir: docs

website:
  title: "MOMENT Lab"
  site-url: https://mao-moment.github.io/

  page-footer:
    left: "&copy; 2026 MOMENT Lab"
    right: "[Privacy Policy](privacy.qmd) · Built with [Quarto](https://quarto.org/)"

  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Teams"
        href: teams.qmd
      - text: "News"
        href: news.qmd
      - text: "Contact Us"
        href: contact.qmd
      - text: "Privacy Policy"
        href: privacy.qmd
      
    
    logo: images/logo_3_nobg.png
    title: false

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left